### ISSUE TITLE
[upcoming branch] Request stream error masks potential server response

### ISSUE THREAD

**Issue by natevw** [natevw/fermata#59]
If CouchDB gets upset, it may simply close the incoming pipe as it sends a repsonse. Rather than getting the response as an error, fermata returns only:

```
{ Error: write EPIPE
    at exports._errnoException (util.js:1007:11)
    at WriteWrap.afterWrite (net.js:793:14) code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }
```

**Comment by natevw** [comment]
To clarify, I think this is talking about a situation where the request is still in progress when the server decides to send its response.

**Comment by natevw** [comment]
This is related to #52 as well.
